name: minedice
version: '1.0-SNAPSHOT'
main: com.edamame.minedice.Minedice
api-version: '1.20'

commands:
  mdice:
    description: さいころを振るコマンドです
    usage: /mdice [面の数] [振る個数(1は省略可)]　で入力してください

  mcr:
    description: チンチロリンをするコマンドです
    usage: /mcr [alone/open/join]　で入力してください